version: '3.4'

services: 
  mutants_crud_api:
    image: golang:1.15-alpine
    container_name: ${API_NAME}
    volumes:
      - go_src:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    environment:
      - GO111MODULE=on
    env_file: 
      - .env
    ports: 
      - "${MUTANTS_CRUD_HTTP_PORT}:${MUTANTS_CRUD_HTTP_PORT}"  
    working_dir: /go/src
    command: sh -c 'cd ${API_BASE_DIR}/${API_NAME};go get -u github.com/beego/bee; go get -v -u ./...; pwd; apk add build-base; go mod init; bee migrate -driver=postgres -conn="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable&search_path=public" || true; go test -coverprofile=coverprofilehelpers.out ./... -coverpkg=./helpers; go test -coverprofile=coverprofilecontrollers.out ./... -coverpkg=./controllers; go test -coverprofile=coverprofilemodels.out ./... -coverpkg=./models; go tool cover -html=coverprofilehelpers.out -o coveragehelpers.html; go tool cover -html=coverprofilecontrollers.out -o coveragecontrollers.html; go tool cover -html=coverprofilemodels.out -o coveragemodels.html; bee run -downdoc=true -gendoc=true'

  data_base:
    container_name: ${MUTANTS_CRUD_PGDB}
    image: postgres:10.15-alpine
    volumes: 
        - postgres_data:/var/lib/postgresql/data
    ports: 
        - "${MUTANTS_CRUD_PGPORT}:${MUTANTS_CRUD_PGPORT}"        
    env_file: 
        - .env

volumes:
  go_src:
  postgres_data: