name: Actions master

on:
  push:
    branches:
      - master

jobs:
  
   build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'

      - name: Clone Repository
        uses: actions/checkout@master

      # - name: Get Dependences
      #   run: GO111MODULE=on && go get -v -u ./...

      # - name: Build and Test
      #   run: go test ./...
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: test
        run: pwd

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: /home/runner/work/api_mutants_mercado_libre/api_mutants_mercado_libre/
          args: >
            -Dsonar.organization=miavega
            -Dsonar.projectKey=Miavega_api_mutants_mercado_libre
            -Dsonar.projectName=api_mutants_mercado_libre
            -Dsonar.projectVersion=0.1
            -Dsonar.language=go
            -Dsonar.exclusions=swagger/**,routers/**,database/**
            -Dsonar.sources=./
            -Dsonar.sources.inclusions=**/**.go
            -Dsonar.test.inclusions=**/**_test.go
            -Dsonar.test.exclusions=database/**
            -Dsonar.sourceEncoding=UTF-8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
   deploy:
    name: Deploy to AWS EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2 Instance
        #run: ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ubuntu@ec2-3-139-102-224.us-east-2.compute.amazonaws.com
        uses: appleboy/ssh-action@master
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
          host: ec2-3-139-102-224.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            ls -al
            git clone https://github.com/Miavega/api_mutants_mercado_libre.git
            cd api_mutants_mercado_libre
            docker-compose down
            git pull
            docker-compose up --build -d
        
      #- name: Deploy code
        #run: ls && printenv