name: Actions master

on:
  push:
    branches:
      - master

jobs:
  
   build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    steps:
      # - name: Setup Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: '1.13'

      # - name: Clone Repository
      #   uses: actions/checkout@v2

      # - name: Get Dependences
      #   run: GO111MODULE=on && go get -v -u ./...

      # - name: Build and Test
      #   run: go test ./...

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: api_mutants_mercado_libre/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
   deploy:
    name: Deploy to AWS EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2 Instance
        #run: ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ubuntu@ec2-3-139-102-224.us-east-2.compute.amazonaws.com
        uses: appleboy/ssh-action@master
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
          host: ec2-3-139-102-224.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            ls -al
            git clone https://github.com/Miavega/api_mutants_mercado_libre.git
            cd api_mutants_mercado_libre
            docker-compose down
            git pull
            docker-compose up --build -d
        
      #- name: Deploy code
        #run: ls && printenv